name: Telegram Notification
on:
  push:
    branches:
      - develop
      - main
jobs:
  notif:
    name: notif
    runs-on: ubuntu-latest
    steps:
      - name: send telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ github.actor }} has a new commit!
            Message: ${{ github.event.head_commit }}

            Repository: https://github.com/${{ github.repository }}

            See Changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            @TheMainMamad | @him_mem_him_dal